baseURL = "https://rotomex.com"
languageCode = "es"
googleAnalytics = "G-4VEFJ6P66C"

# ------------------------------
theme = "rotomex"
title = "Rotomex"


[params]
  author = "Espumas y Materiales Industriales SA de CV"
  description = "Somos una empresa con mas de 20 a&ntilde;os de experiencia en la industria del rotomoldeo."

# ------------------------------

# needed to  render raw HTML (e.g. <sub>, <sup>, <kbd>, <mark>)
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[taxonomies]
category = "categories"
tag = "tags"
series = "series"

